# Generated by Django 5.0.4 on 2024-09-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('name', models.CharField(max_length=25)),
                ('assignedto', models.CharField(max_length=20)),
                ('priority', models.IntegerField(verbose_name='10')),
            ],
        ),
    ]
